=== Zehl41/HLC-TO1/xml/torneos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="torneos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="torneo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="modalidades">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modalidad" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cantidad_equipos" type="xs:integer"/>
                            <xs:element name="pros" type="xs:integer"/>
                            <xs:element name="contras" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique_numero">
            <xs:selector xpath="torneo"/>
            <xs:field xpath="@numero"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== Zehl41/HLC-TO1/xml/torneos_instanciado.xml
<?xml version="1.0" encoding="UTF-8"?>
<torneos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="torneos.xsd">

    <torneo numero="1">
        <nombre>Mundial de Qatar</nombre>
        <modalidades>
            <modalidad>Grupos</modalidad>
            <modalidad>Eliminatoria</modalidad>
        </modalidades>
        <cantidad_equipos>32</cantidad_equipos>
        <pros>2</pros>
        <contras>3</contras>
    </torneo>
    <torneo numero="2">
        <nombre>NBA</nombre>
        <modalidades>
            <modalidad>Liga</modalidad>
            <modalidad>Eliminatoria</modalidad>
        </modalidades>
        <cantidad_equipos>30</cantidad_equipos>
        <pros>2</pros>
        <contras>3</contras>
    </torneo>
    <torneo numero="3">
        <nombre>Mundial de F1</nombre>
        <modalidades>
            <modalidad>Grandes premios</modalidad>
        </modalidades>
        <cantidad_equipos>10</cantidad_equipos>
        <pros>1</pros>
        <contras>1</contras>
    </torneo>
    <torneo numero="4">
        <nombre>Major de CSGO</nombre>
        <modalidades>
            <modalidad>Grupos</modalidad>
            <modalidad>Eliminatoria</modalidad>
        </modalidades>
        <cantidad_equipos>24</cantidad_equipos>
        <pros>4</pros>
        <contras>0</contras>
    </torneo>
    <torneo numero="5">
        <nombre>Mundial de Ajedrez</nombre>
        <modalidades>
            <modalidad>Liga</modalidad>
        </modalidades>
        <cantidad_equipos>2</cantidad_equipos>
        <pros>1</pros>
        <contras>0</contras>
    </torneo>
</torneos>
